# Generated by Django 5.0 on 2023-12-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='explore.category')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('prog_id', models.AutoField(primary_key=True, serialize=False)),
                ('prog_name', models.CharField(max_length=255)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='explore.category')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='explore.location')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('fos_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_study', to='explore.programs')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='explore.category')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='explore.location')),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='explore.programs')),
            ],
        ),
    ]
