# Generated by Django 3.1 on 2023-12-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_fieldofstudy_uni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldofstudy',
            old_name='uni',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='uni_id',
            new_name='university_id',
        ),
    ]
