# Generated by Django 3.1 on 2023-12-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_auto_20231207_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='prog',
        ),
        migrations.RemoveField(
            model_name='university',
            name='prog',
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
    ]
