# Generated by Django 3.1 on 2023-12-13 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_auto_20231213_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_study', to='explore.category'),
            preserve_default=False,
        ),
    ]
