# Generated by Django 3.1 on 2023-12-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0009_auto_20231213_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='university',
            name='cat',
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='categories',
            field=models.ManyToManyField(related_name='fields_of_study', to='explore.Tag'),
        ),
        migrations.AddField(
            model_name='university',
            name='categories',
            field=models.ManyToManyField(related_name='universities', to='explore.Tag'),
        ),
    ]
