# Generated by Django 4.2.8 on 2023-12-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_auto_20231214_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='university',
            name='categories',
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_study', to='explore.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='explore.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='explore.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
