# Generated by Django 4.2.8 on 2023-12-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_remove_fieldofstudy_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='university',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='university',
            name='loc',
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='categories',
            field=models.ManyToManyField(related_name='fields_of_study', to='explore.category'),
        ),
        migrations.AddField(
            model_name='university',
            name='categories',
            field=models.ManyToManyField(related_name='universities', to='explore.category'),
        ),
        migrations.AddField(
            model_name='university',
            name='locations',
            field=models.ManyToManyField(related_name='universities', to='explore.location'),
        ),
    ]
