# Generated by Django 4.2.8 on 2023-12-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0012_remove_fieldofstudy_cat_remove_university_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('prog_id', models.AutoField(primary_key=True, serialize=False)),
                ('prog_name', models.CharField(max_length=255)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='explore.category')),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='programs',
            field=models.ManyToManyField(related_name='universities', to='explore.programs'),
        ),
    ]
