# Generated by Django 5.0 on 2023-12-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0014_remove_fieldofstudy_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
